// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const borderWidths = {
 "hairline": "1px",
 "regular": "1.5px",
 "thick": "2.5px"
} as const;

export default borderWidths;