// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const colors = {
 "yellow": "rgba(255, 206, 0, 1)",
 "black": "rgba(48, 49, 51, 1)",
 "white": "rgba(255, 255, 255, 1)",
 "faintBeige": "rgba(250, 246, 241, 1)",
 "lightBeige": "rgba(243, 236, 226, 1)",
 "beige": "rgba(190, 176, 162, 1)",
 "gray": "rgba(204, 204, 204, 1)",
 "darkGrey": "rgba(89, 90, 92, 1)",
 "lightYellow": "rgba(255, 230, 128, 1)",
 "green": "rgba(94, 115, 97, 1)",
 "red": "rgba(225, 38, 28, 1)",
 "blue": "rgba(0, 72, 119, 1)",
 "olive": "rgba(180, 184, 150, 1)",
 "darkRed": "rgba(191, 36, 27, 1)",
 "lightRed": "rgba(243, 168, 164, 1)"
} as const;

export default colors;