// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontFamilies = {
 "numbersSmall": "MuseoSans-700",
 "numbersLarge": "MuseoSans-700",
 "primaryCaption12": "MuseoSans-500",
 "primaryCaption12500": "MuseoSans-500",
 "primaryCaption12900": "MuseoSans-900",
 "secondaryBody14500": "MuseoSans-500",
 "secondaryBody14700": "MuseoSans-700",
 "secondaryBody14900": "MuseoSans-900",
 "primaryBody16500": "MuseoSans-500",
 "primaryBody16700": "MuseoSans-700",
 "primaryBody16900": "MuseoSans-900",
 "primarySubhead18700": "MuseoSans-700",
 "primarySubhead18900": "MuseoSans-900",
 "secondarySubhead18700": "MuseoSans-700",
 "secondarySubhead18900": "MuseoSans-900",
 "primarySubhead22": "MuseoSans-900",
 "secondaryHeader22Mu": "MuseoSans-900",
 "secondaryHeader22Noto": "NotoSerif-ExtraBold",
 "primaryHeader30Mu": "MuseoSans-900",
 "primaryHeader30Noto": "NotoSerif-ExtraBold",
 "secondaryHeader30Mu": "MuseoSans-900",
 "secondaryHeader30Noto": "NotoSerif-ExtraBold",
 "primaryHeader36Mu": "MuseoSans-900",
 "primaryHeader36Noto": "NotoSerif-ExtraBold",
 "tertiaryHeader30Mu": "MuseoSans-900",
 "secondaryHeader36Mu": "MuseoSans-900",
 "secondaryHeader36Noto": "NotoSerif-ExtraBold",
 "primaryHeader48Mu": "MuseoSans-900",
 "primaryHeader48Noto": "NotoSerif-ExtraBold"
} as const;

export default fontFamilies;