// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const opacities = {
 "transparent": 0,
 "semiOpaque50": 0.5,
 "semiOpaque75": 0.75,
 "opaque": 1
} as const;

export default opacities;