// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const spacing = {
 "spacing1": "30.625rem",
 "spacing2": "30.625rem",
 "spacing3": "30.625rem",
 "spacing4": "30.625rem",
 "spacing5": "30.625rem",
 "spacing6": "30.625rem",
 "spacing7": "30.625rem",
 "spacing8": "30.625rem",
 "spacing9": "30.625rem",
 "spacing10": "30.625rem",
 "spacing11": "30.625rem",
 "spacing12": "30.625rem"
} as const;

export default spacing;